export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, params }) {
  return (
    <html lang="en">
      <body>
        <h1 className="font-mono font-bold">
          Host: {params.host}
          {` `}Lang: {params.lang}
        </h1>
        {children}
      </body>
    </html>
  );
}
